services:
  qr-printer:
    image: tynen/qr2paper:latest
    ports:
      - "5000:5000"
    environment:
      - PRINTER_URI=ipp://PRINTERIP/ipp/print
      - FLASK_ENV=production
    # No need to mount host CUPS socket, container runs its own CUPS
